#build phase block
FROM node:alpine as builder
WORKDIR '/app'
COPY ./package.json ./
RUN npm intall
COPY . .
RUN npm run build

#run phase block
FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
